routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();
Route::get('/', 'CatalogsController@index');
Route::get('/home', 'HomeController@index');
Route::resource('categories', 'CategoriesController');
Route::resource('/catalogs', 'CatalogsController');
Route::resource('products', 'ProductsController');
Route::post('cart', 'CartController@addProduct');
Route::get('cart', 'CartController@show');
Route::delete('cart/{product_id}', 'CartController@removeProduct');
Route::put('cart/{product_id}', 'CartController@changeQuantity');
Route::get('checkout/login', 'CheckoutController@login');
Route::post('checkout/login', 'CheckoutController@postLogin');
Route::get('checkout/address', function() {
    return "Email customer " . session()->get('checkout.email');
});

Route::get('checkout/address', 'CheckoutController@address');
Route::post('checkout/address', 'CheckoutController@postAddress');
Route::get('checkout/payment', 'CheckoutController@payment');
Route::post('checkout/payment', 'CheckoutController@postPayment');
Route::get('checkout/success', 'CheckoutController@success');

Route::resource('orders', 'OrdersController', ['only' => [
    'index', 'edit', 'update'
]]);

Route::get('/home/orders', 'HomeController@viewOrders');

Route::group(['middleware' => 'api'], function () {
    Route::get('address/regencies', 'AddressController@regencies');
});

resources/views/layouts/_cart-menu-bar.blade.php
<li>
	<a href="{{ url('/cart') }}">
	<i class="fa fa-shopping-cart"></i> 
	Cart {{ $cart->totalProduct() > 0 ? '(' . $cart->totalProduct() . ')' : ''}}
	</a>
</li>

resources/views/layouts/_check-order-menu-bar.blade.php
<li><a href="{{ url('/home/orders') }}">Cek Order</a></li>

resources/views/layouts/_customer-feature.blade.php
@can('customer-access')
  @include($partial_view, isset($data) ? $data : [])
@else
  @if (auth()->guest())
    @include($partial_view, isset($data) ? $data : [])
  @endif
@endcan

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link rel="stylesheet" href="{{ mix('assets/css/app.css') }}">
    <link rel="stylesheet" href="{{ mix('assets/css/libs.css') }}">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    <style type="text/css">
        
    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                      @if(Auth::check())
                        
                        @can('admin-access')
                            <li><a href="{{ url('/home') }}">Dashboard</a></li>
                            <li><a href="{{ route('categories.index') }}">Categories</a></li>
                            <li><a href="{{ route('products.index') }}">Products</a></li>
                            <li><a href="{{ route('orders.index') }}">Orders</a></li>
                        @endcan
                      @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">

                      @include('layouts._customer-feature', ['partial_view'=>'layouts._check-order-menu-bar', 'data'=>[]])

                      @include('layouts._customer-feature', ['partial_view'=>'layouts._cart-menu-bar'])

                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

          <div class="container">
            @include('flash::message')
          </div>

        @yield('content')

    </div>

    <!-- Scripts -->
    <script src="{{ mix('assets/js/app.js') }}"></script>
    <script src="{{ mix('assets/js/all.js') }}"></script>
    <script src="{{ mix('assets/js/libs.js') }}"></script>
    <script src="{{ mix('assets/js/custom.js') }}"></script>

    @if (Session::has('flash_product_name'))
      @include('catalogs._product-added', ['product_name' => Session::get('flash_product_name')])
    @endif
</body>
</html>